In [5]:
print(os.listdir(r"D:\Asad_Study\Data Analyst projects Learning\Sql_Project"))

['Books.csv', 'Customers.csv', 'Day – 30 – SQL – Project on SQL Only Questions.sql', 'desktop.ini', 'Orders.csv', 'SQL Project Questions Day 30.pdf']

In [6]:
import mysql.connector
from mysql.connector import Error
import os

# Get password from environment variable
pwd = os.getenv("MYSQL_PWD")  # e.g., your actual MySQL password stored in env

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
#     password="",
    password=pwd,  # <- no quotes here!
    # <- no quotes here!
    database="books_store",
    allow_local_infile=True
)

cursor = conn.cursor()
print("✅ Connected to MySQL and database is ready")

✅ Connected to MySQL and database is ready

In [7]:
import pandas as pd

file_path1 = r"D:\Asad_Study\Data Analyst projects Learning\Sql_Project\Books.csv"
file_path2 = r"D:\Asad_Study\Data Analyst projects Learning\Sql_Project\Customers.csv"
file_path3 = r"D:\Asad_Study\Data Analyst projects Learning\Sql_Project\Orders.csv"

df_Books = pd.read_csv(file_path1)
df_Customers = pd.read_csv(file_path2)
df_Orders = pd.read_csv(file_path3)

df_Books.head()

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16

In [ ]:
cursor.execute("DROP TABLE IF EXISTS Orders;")
conn.commit()

In [ ]:
cursor.execute("DROP TABLE IF EXISTS Books;")

In [ ]:
cursor.execute("DROP TABLE IF EXISTS Customers;")
conn.commit()

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Books (
    Book_ID INT PRIMARY KEY,
    Title VARCHAR(100),
    Author VARCHAR(100),
    Genre VARCHAR(50),
    Published_Year INT,
    Price DECIMAL(10,2),
    Stock INT
) ENGINE=InnoDB;
""")

conn.commit()

In [ ]:
df_Books.head()

In [ ]:


# Insert data into Books
for _, row in df_Books.iterrows():
    cursor.execute("""
        INSERT INTO Books (Book_ID,Title, Author, Genre, Published_Year, Price, Stock)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
    """, tuple(row))
conn.commit()

In [ ]:
df_Customers.head()

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Customers (
    Customer_ID INT PRIMARY KEY,
    Name VARCHAR(100),
    Email VARCHAR(100),
    Phone INT,
    City VARCHAR(50),
    Country VARCHAR(100)
) ENGINE=InnoDB;


""")
conn.commit()

In [ ]:

# Insert data into Customers
for _, row in df_Customers.iterrows():
    cursor.execute("""
        INSERT INTO Customers (Customer_ID, Name, Email,  Phone, City, Country)
        VALUES (%s, %s, %s, %s, %s, %s)
    """, tuple(row))
conn.commit()

In [ ]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS Orders (
    Order_ID INT AUTO_INCREMENT PRIMARY KEY,
    Customer_ID INT,
    Book_ID INT,
    OrderDate DATE,
    Quantity INT,
    Total_Amount DECIMAL(10,2),
    FOREIGN KEY (Customer_ID) REFERENCES Customers(Customer_ID),
    FOREIGN KEY (Book_ID) REFERENCES Books(Book_ID)
) ENGINE=InnoDB;
""")
conn.commit()

In [ ]:
# Insert data into Orders
for _, row in df_Orders.iterrows():
    cursor.execute("""
        INSERT INTO Orders (Order_ID, Customer_ID, Book_ID, OrderDate, Quantity, Total_Amount)
        VALUES (%s, %s, %s, %s,%s, %s)
    """, tuple(row))
conn.commit()

print("✅ All data inserted successfully!")

In [ ]:

query = "SELECT * FROM Books WHERE Genre = 'Fiction';"
df = pd.read_sql_query(query, conn)

df.head(3)
cursor.close()

In [14]:
df=pd.read_sql_query("Describe books",conn)
df

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\555746522.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("Describe books",conn)

            Field           Type Null  Key Default Extra
0         Book_ID            int   NO  PRI    None
1           Title   varchar(100)  YES         None
2          Author   varchar(100)  YES         None
3           Genre    varchar(50)  YES         None
4  Published_Year            int  YES         None
5           Price  decimal(10,2)  YES         None
6           Stock            int  YES         None

In [17]:
# -- 1) Retrieve all books in the "Fiction" genre:
df=pd.read_sql_query("SELECT * FROM books WHERE Genre='Fiction' ", conn)
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\3284961321.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("SELECT * FROM books WHERE Genre='Fiction' ", conn)

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
1,22,Multi-layered optimizing migration,Wesley Escobar,Fiction,1908,39.23,78
2,28,Expanded analyzing portal,Lisa Coffey,Fiction,1941,37.51,79
3,29,Quality-focused multi-tasking challenge,Katrina Underwood,Fiction,1905,31.12,100
4,31,Implemented encompassing conglomeration,Melissa Taylor,Fiction,2010,21.23,44

In [18]:
# -- 2) Find books published after the year 1950:

df=pd.read_sql_query("SELECT * FROM books WHERE Published_Year>1950 ", conn)
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\2103690834.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("SELECT * FROM books WHERE Published_Year>1950 ", conn)

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
1,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
2,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16
3,6,Advanced encompassing implementation,Bryan Morgan,Biography,1985,6.56,2
4,8,Persistent local encoding,Troy Cox,Science Fiction,2019,48.99,84

In [19]:
df=pd.read_sql_query("Describe customers",conn)
df

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\1703381368.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("Describe customers",conn)

         Field          Type Null  Key Default Extra
0  Customer_ID           int   NO  PRI    None
1         Name  varchar(100)  YES         None
2        Email  varchar(100)  YES         None
3        Phone           int  YES         None
4         City   varchar(50)  YES         None
5      Country  varchar(100)  YES         None

In [20]:
# -- 3) List all customers from the Canada:
df=pd.read_sql_query("SELECT * FROM customers WHERE Country='Canada'",conn)
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\3905062462.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("SELECT * FROM customers WHERE Country='Canada'",conn)

,Customer_ID,Name,Email,Phone,City,Country
0,38,Nicholas Harris,christine93@perkins.com,1234567928,Davistown,Canada
1,415,James Ramirez,robert54@hall.com,1234568305,Maxwelltown,Canada
2,468,David Hart,stokesrebecca@gmail.com,1234568358,Thompsonfurt,Canada

In [26]:
df=pd.read_sql_query("Describe orders",conn)
df

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\4222222958.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("Describe orders",conn)

          Field           Type Null  Key Default           Extra
0      Order_ID            int   NO  PRI    None  auto_increment
1   Customer_ID            int  YES  MUL    None
2       Book_ID            int  YES  MUL    None
3     OrderDate           date  YES         None
4      Quantity            int  YES         None
5  Total_Amount  decimal(10,2)  YES         None

In [31]:
df=pd.read_sql_query("SELECT * FROM Orders",conn)
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\3555434136.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("SELECT * FROM Orders",conn)

   Order_ID  Customer_ID  Book_ID   OrderDate  Quantity  Total_Amount
0         1           84      169  2023-05-26         8        188.56
1         2          137      301  2023-01-23        10        216.60
2         3          216      261  2024-05-27         6         85.50
3         4          433      343  2023-11-25         7        301.21
4         5           14      431  2023-07-26         7        136.36

In [33]:
# -- 4) Show orders placed in November 2023:
df = pd.read_sql_query("""
SELECT *
FROM orders
WHERE OrderDate BETWEEN '2023-11-01' AND '2023-11-30'
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\1034528097.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

   Order_ID  Customer_ID  Book_ID   OrderDate  Quantity  Total_Amount
0         4          433      343  2023-11-25         7        301.21
1        19          496       60  2023-11-17         9        316.26
2        75          291      375  2023-11-30         5        170.75
3       132          469      333  2023-11-22         7        194.32
4       137          474      471  2023-11-25         8        363.04

In [35]:
df=pd.read_sql_query("SELECT * FROM books",conn)
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\568772938.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("SELECT * FROM books",conn)

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16

In [37]:
# -- 5) Retrieve the total stock of books available:

df=pd.read_sql_query("SELECT SUM(Stock) AS Total_Stock FROM books",conn)
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\2754763529.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("SELECT SUM(Stock) AS Total_Stock FROM books",conn)

   Total_Stock
0      25056.0

In [47]:
# -- 6) Find the details of the most expensive book:
df=pd.read_sql_query("""SELECT *  
FROM books
where price = (Select Max(price) from books)""",conn)
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\1583668428.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("""SELECT *

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,340,Proactive system-worthy orchestration,Robert Scott,Mystery,1907,49.98,88

In [49]:
#  7) Show all customers who ordered more than 1 quantity of a book:


df=pd.read_sql_query("""
SELECT c.Name 
FROM customers c 
JOIN orders o 
    ON c.Customer_ID=o.order_ID
WHERE quantity>1  
""",conn)
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\1213677337.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("""

               Name
0  Deborah Griffith
1  Crystal Clements
2      Susan Fuller
3     Jamie Ramirez
4     Marcus Murphy

In [50]:
df=pd.read_sql_query("SELECT * FROM Orders",conn)
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\3555434136.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("SELECT * FROM Orders",conn)

   Order_ID  Customer_ID  Book_ID   OrderDate  Quantity  Total_Amount
0         1           84      169  2023-05-26         8        188.56
1         2          137      301  2023-01-23        10        216.60
2         3          216      261  2024-05-27         6         85.50
3         4          433      343  2023-11-25         7        301.21
4         5           14      431  2023-07-26         7        136.36

In [53]:
# 8) Retrieve all orders where the total amount exceeds $20:
df=pd.read_sql_query("""
SELECT *
FROM orders
WHERE Total_Amount>20
""",conn)
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\865590908.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("""

   Order_ID  Customer_ID  Book_ID   OrderDate  Quantity  Total_Amount
0         1           84      169  2023-05-26         8        188.56
1         2          137      301  2023-01-23        10        216.60
2         3          216      261  2024-05-27         6         85.50
3         4          433      343  2023-11-25         7        301.21
4         5           14      431  2023-07-26         7        136.36

In [82]:
# 8) Retrieve all orders where the total amount exceeds $20:
df=pd.read_sql_query("""
SELECT *
FROM orders
WHERE Total_Amount>20
""",conn)
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\865590908.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("""

   Order_ID  Customer_ID  Book_ID   OrderDate  Quantity  Total_Amount
0         1           84      169  2023-05-26         8        188.56
1         2          137      301  2023-01-23        10        216.60
2         3          216      261  2024-05-27         6         85.50
3         4          433      343  2023-11-25         7        301.21
4         5           14      431  2023-07-26         7        136.36

In [57]:

# -- 9) List all genres available in the Books table:



df = pd.read_sql_query("""
SELECT DISTINCT Genre
FROM books
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\3347278488.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

         Genre
0    Biography
1      Fantasy
2  Non-Fiction
3      Fiction
4      Romance

In [61]:
# -- 10) Find the book with the lowest stock:



df = pd.read_sql_query("""
SELECT *
FROM books
WHERE Stock = (SELECT MIN(Stock) FROM books)
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\500739515.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,44,Networked systemic implementation,Ryan Frank,Science Fiction,1965,13.55,0
1,60,Robust eco-centric capacity,Brian Haney,Biography,1990,35.14,0
2,127,Business-focused real-time benchmark,David Nelson,Science Fiction,1997,11.66,0
3,163,Object-based eco-centric challenge,Douglas Mccarthy,Non-Fiction,1905,19.11,0
4,378,Future-proofed heuristic function,Samantha Mcclain,Romance,1903,6.01,0

In [68]:
# -- 11) Calculate the total revenue generated from all orders:
df = pd.read_sql_query("""
SELECT  SUM(Total_Amount) AS Revenue
 FROM Orders
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\1931811090.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

    Revenue
0  75628.66

In [74]:
# -- 1) Retrieve the total number of books sold for each genre:
df = pd.read_sql_query("""
SELECT  SUM(o.Quantity),b.Genre
FROM books b
JOIN orders o 
    ON b.Book_ID = o.Book_ID
group by Genre    
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\3252720851.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

   SUM(o.Quantity)            Genre
0            285.0        Biography
1            446.0          Fantasy
2            447.0  Science Fiction
3            504.0          Mystery
4            439.0          Romance

In [78]:
# -- 2) Find the average price of books in the "Fantasy" genre:

df = pd.read_sql_query("""
SELECT  AVG(Price) AS Avg_Price
FROM books 
WHERE Genre='Fantasy' 
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\2763852290.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

   Avg_Price
0   25.98169

In [88]:
# -- 3) List customers who have placed at least 2 orders:

df = pd.read_sql_query("""
SELECT c.Name, COUNT(O.Order_ID) AS NUM_OF_Orders FROM orders o
JOIN Customers c
    ON o.Customer_ID=c.Customer_ID
GROUP BY c.Name
HAVING COUNT(O.Order_ID)>= 2
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\4030237162.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

               Name  NUM_OF_Orders
0  Crystal Clements              2
1   Stephen Vasquez              2
2   Matthew Johnson              2
3     Thomas Garcia              3
4      Kristine Kim              2

In [89]:
df = pd.read_sql_query("""
SELECT  *
 FROM Orders
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\1495034640.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

   Order_ID  Customer_ID  Book_ID   OrderDate  Quantity  Total_Amount
0         1           84      169  2023-05-26         8        188.56
1         2          137      301  2023-01-23        10        216.60
2         3          216      261  2024-05-27         6         85.50
3         4          433      343  2023-11-25         7        301.21
4         5           14      431  2023-07-26         7        136.36

In [90]:
df = pd.read_sql_query("""
SELECT  *
 FROM Books
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\1590764413.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16

In [94]:
#  4) Find the most frequently ordered book:
df = pd.read_sql_query("""
SELECT  Count(o.Order_ID) AS Num_Of_Orders
FROM orders o
JOIN books b
    ON o.Book_ID=b.Book_ID
Group by Title
Order by Num_Of_Orders DESC
LIMIT 1
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\2166041589.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

   Num_Of_Orders
0              4

In [95]:
df = pd.read_sql_query("""
SELECT  *
 FROM Books
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\1590764413.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16

In [102]:
df = pd.read_sql_query("""
SELECT  *
 FROM Orders
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\1495034640.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

   Order_ID  Customer_ID  Book_ID   OrderDate  Quantity  Total_Amount
0         1           84      169  2023-05-26         8        188.56
1         2          137      301  2023-01-23        10        216.60
2         3          216      261  2024-05-27         6         85.50
3         4          433      343  2023-11-25         7        301.21
4         5           14      431  2023-07-26         7        136.36

In [100]:
# - 5) Show the top 3 most expensive books of 'Fantasy' Genre :

df = pd.read_sql_query("""
SELECT Title, Price
FROM Books
WHERE Genre = 'Fantasy'
ORDER BY Price DESC
LIMIT 3
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\1774633592.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

                               Title  Price
0      Stand-alone content-based hub  49.90
1  Innovative 3rdgeneration database  49.23
2     Optimized even-keeled analyzer  48.97

In [104]:
# -- 6) Retrieve the total quantity of books sold by each author:
df = pd.read_sql_query("""
SELECT 
    b.Author,
    SUM(o.Quantity) AS Total_Books_Sold
FROM Books b
JOIN Orders o 
    ON b.Book_ID = o.Book_ID
GROUP BY b.Author
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\458080143.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

                Author  Total_Books_Sold
0       Margaret Moore               8.0
1        John Davidson              13.0
2  Christopher Fuentes               6.0
3        Marissa Smith              16.0
4    Christopher Dixon              15.0

In [106]:
df = pd.read_sql_query("""
SELECT  *
 FROM customers
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\2611758084.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

,Customer_ID,Name,Email,Phone,City,Country
0,1,Deborah Griffith,balljoseph@wright-keith.net,1234567891,South Craigfort,Denmark
1,2,Crystal Clements,kimberlybennett@curtis.com,1234567892,East Derekberg,Nicaragua
2,3,Susan Fuller,beanmichael@burnett-stewart.net,1234567893,Austinbury,Equatorial Guinea
3,4,Jamie Ramirez,amandahood@warren.com,1234567894,Dianamouth,Slovenia
4,5,Marcus Murphy,connerjohn@yahoo.com,1234567895,Smithbury,Guinea-Bissau

In [107]:
# -- 7) List the cities where customers who spent over $30 are located:

df = pd.read_sql_query("""
SELECT 
    c.City,
    SUM(o.Total_Amount) AS Total_Spent
FROM Customers c
JOIN Orders o 
    ON c.Customer_ID = o.Customer_ID
GROUP BY c.City
HAVING SUM(o.Total_Amount) > 30
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\1874382897.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

              City  Total_Spent
0        Lake Paul       231.68
1      North Keith       286.92
2       Kelseyfort       157.80
3       East David       301.21
4  Richardsonville       383.06

In [116]:
# -- 8) Find the customer who spent the most on orders:

df=pd.read_sql_query("""
SELECT c.Name, Max(Total_Amount) As most_spent_amount
FROM customers c
JOIN orders o 
    ON c.Customer_ID = o.Customer_ID
Group by c.Customer_ID    
order by most_spent_amount Desc
Limit 3
""",conn)
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\2014432007.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("""

                  Name  most_spent_amount
0  Christine Maldonado              491.5
1       Jason Villegas              489.6
2        Kevin Collins              489.6

In [118]:
df = pd.read_sql_query("""
SELECT  *
 FROM Orders
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\1495034640.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

   Order_ID  Customer_ID  Book_ID   OrderDate  Quantity  Total_Amount
0         1           84      169  2023-05-26         8        188.56
1         2          137      301  2023-01-23        10        216.60
2         3          216      261  2024-05-27         6         85.50
3         4          433      343  2023-11-25         7        301.21
4         5           14      431  2023-07-26         7        136.36

In [117]:
df = pd.read_sql_query("""
SELECT  *
 FROM books
""", conn)

df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\796084614.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16

In [120]:
# --9) Calculate the stock remaining after fulfilling all orders:
df = pd.read_sql_query("""
SELECT 
    b.Book_ID,
    b.Title,
    b.Stock - IFNULL(SUM(o.Quantity), 0) AS Stock_Remaining
FROM Books b
LEFT JOIN Orders o 
    ON b.Book_ID = o.Book_ID
GROUP BY b.Book_ID, b.Title, b.Stock
ORDER BY Stock_Remaining ASC
""", conn)

df.head()

# 🧠 Explanation

# LEFT JOIN → includes all books, even those with no orders.

# SUM(o.Quantity) → total number of copies sold for that book.

# IFNULL(..., 0) → replaces NULL with 0 if a book has no orders.

# b.Stock - SUM(o.Quantity) → remaining stock after orders.

# ORDER BY Stock_Remaining ASC → books with lowest stock first.

C:\Users\admin\AppData\Local\Temp\ipykernel_9148\2661062961.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

   Book_ID                                          Title  Stock_Remaining
0      491                 Pre-emptive intangible adapter            -18.0
1      307                  Expanded local infrastructure            -16.0
2      288  Re-contextualized real-time Graphic Interface            -14.0
3      323                       Balanced dynamic project            -14.0
4      110               Re-contextualized radical matrix            -13.0